# Generated by Django 4.1 on 2022-08-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=30, verbose_name="Название категории"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="", verbose_name="Изображение карты"),
                ),
                (
                    "location_name",
                    models.CharField(max_length=30, verbose_name="Название локации"),
                ),
                (
                    "type_of_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wild", "Дикие земли"),
                            ("siege", "Осада"),
                            ("adventure", "Приключения"),
                            ("temple", "Храм"),
                        ],
                        max_length=9,
                        verbose_name="Тип локации локации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта",
                "verbose_name_plural": "Карты",
                "ordering": ("location_name", "type_of_location"),
            },
        ),
        migrations.CreateModel(
            name="Dot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x_coordinate",
                    models.FloatField(max_length=10, verbose_name="Х координата"),
                ),
                (
                    "y_coordinate",
                    models.FloatField(max_length=10, verbose_name="Y координата"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Цвет точки"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Название для точки"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Описание для точки"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Иконка точки"
                    ),
                ),
                ("category", models.ManyToManyField(to="Map.category")),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Map.map",
                        verbose_name="Карта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка на карте",
                "verbose_name_plural": "Точки на карте",
                "ordering": ("name", "description"),
            },
        ),
    ]
